version: "3.7"

services:
  yearn-exporter-api:
    build: .
    image: ghcr.io/mariuspod/yearn-exporter-api
    ports:
      - 127.0.0.1:${FLASK_RUN_PORT:-5000}:${FLASK_RUN_PORT:-5000}
    environment:
      - FLASK_APP=api
      - FLASK_RUN_PORT=${FLASK_RUN_PORT:-5000}
      - BASE_URL=${BASE_URL:-https://yearn.vision}
    restart: unless-stopped
